from . import freight_shipping_line
from . import freight_port
from . import freight_charge_type
from . import freight_container
from . import freight_charge
from . import freight_shipment
from . import freight_shipment_leg
from . import freight_tariff
from . import res_config_settings
